# Generated by Django 2.1.2 on 2018-10-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('nombreMascota', models.CharField(max_length=30)),
                ('tamaño', models.CharField(choices=[('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande')], default='M', max_length=1)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=3)),
                ('color', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('S', 'Adoptado'), ('N', 'No Adoptado')], default='N', max_length=1)),
            ],
        ),
    ]
