# Generated by Django 2.1.2 on 2018-10-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioAdopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
