# Generated by Django 2.1.2 on 2018-10-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioAdopcion', '0003_auto_20181027_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='fechaRescate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('R', 'Rescatado'), ('D', 'Disponible'), ('A', 'Adoptado')], default='D', max_length=1),
        ),
    ]
