# Generated by Django 2.1.2 on 2018-10-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioAdopcion', '0004_auto_20181027_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fechaRescate',
            field=models.DateField(),
        ),
    ]
